---
channel: stable
addons:
  mailserver:
    repository: scanearth/addon-mail
    target: mail
    image: ghcr.io/scanearth/mailserver/{arch}
  mailfilter:
    repository: scanearth/addon-mailfilter
    target: mailfilter
    image: ghcr.io/scanearth/mailfilter/{arch}
